server:
  port: 9001
spring:
  application:
    name: tensquare-base #指定服务名  后续springcloud 不能有下划线
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.129:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: true